# Generated by Django 4.1.4 on 2023-01-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fde.m.wikipedia.org%2Fwiki%2FDatei%3APlaceholder_view_vector.svg&psig=AOvVaw1MzyS2aATNabxUz5AH9SQK&ust=1672765693451000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCKDPuvqvqfwCFQAAAAAdAAAAABAD', max_length=1000),
        ),
    ]
