# Generated by Django 4.1.4 on 2023-01-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/3/3f/Placeholder_view_vector.svg', max_length=1000),
        ),
    ]
