# Generated by Django 4.1.4 on 2023-01-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://i0.wp.com/laryloves.com/wp-content/uploads/woocommerce-placeholder.png', max_length=1000),
        ),
    ]
